---
- name: Check ansible version
  ansible.builtin.debug:
    msg: "This role works best with ansible version 2.8 or greater. It is recommended to use the latest ansible version for the best experience."
  when:
    - ansible_version.full is version_compare('2.8', '<')

# Create a sync-only device group with auto-sync enabled
- name: Create a sync-only device group with auto-sync enabled
  bigip_device_group:
    name: foo-group
    auto_sync: yes
    provider:
      password: secret
      server: 1.1.1.1
      user: admin
  delegate_to: localhost
