---
- name: Check ansible version
  ansible.builtin.debug:
    msg: "This role works best with ansible version 2.8 or greater. It is recommended to use the latest ansible version for the best experience."
  when:
    - ansible_version.full is version_compare('2.8', '<')

- name: Create virtual server
  f5networks.f5_modules.bigip_virtual_server:
    name: virt1
    destination: 2.1.3.4
    port: 9000
    description: My virtual server
    snat: Automap
    pool: pool1
    provider:
      user: admin
      server: 1.1.1.1
      password: secret
      validate_certs: no
  register: result

- name: Create virtual server with var
  f5networks.f5_modules.bigip_virtual_server:
    name: virt2
    destination: 2.1.3.5
    port: 0
    provider: "{{ provider }}"

# Collect BIG-IP information
- name: Collect BIG-IP information
  f5networks.f5_modules.bigip_device_info:
    gather_subset:
      - interfaces
      - vlans
    provider:
      server: 1.1.1.1
      user: admin
      password: secret
  delegate_to: localhost

- name: Collect all BIG-IP information
  f5networks.f5_modules.bigip_device_info:
    gather_subset:
      - all
    provider:
      server: 1.1.1.1
      user: admin
      password: secret
  delegate_to: localhost

- name: Collect all BIG-IP information except trunks
  f5networks.f5_modules.bigip_device_info:
    gather_subset:
      - all
      - "!trunks"
    provider:
      server: 1.1.1.1
      user: admin
      password: secret
  delegate_to: localhost

# Create a sync-only device group with auto-sync enabled
- name: Create a sync-only device group with auto-sync enabled
  bigip_device_group:
    name: foo-group
    auto_sync: yes
    provider:
      password: secret
      server: 1.1.1.1
      user: admin
  delegate_to: localhost
