---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    provider:
      user: admin
      server: "{{ ansible_host }}"
      server_port: 443
      password: admin
      validate_certs: no

  roles:
    - role: buluma.f5ansible
